### ISSUE TITLE
Dynamic insertion of hx-tabs

### ISSUE THREAD

**Issue by jreeter** [rackerlabs/helix-ui#443] opened 2019-02-01 22:14 UTC
## Describe the Bug
Dynamically inserting tabs and its panel result in the tab not functioning. User cannot click and open the tab panel.

## Steps to Reproduce
1. Clone this repo: https://github.com/jreeter/dynamic-hx-tabs
2. Run `npm i`
3. Run `ng serve`
4. Navigate to localhost:4200
5. Click the add tab button.
6. The new tab will not load the tab panel when clicked.

## Expected behavior
I expect dynamically added tabs to function and show the corresponding tab panel.

## Screenshots
<img width="278" alt="screen shot 2019-02-01 at 4 07 19 pm" src="https://user-images.githubusercontent.com/1757798/52152359-c6b22380-263b-11e9-9460-074e54f57764.png">

## Environment
Please complete the following information:

 - Device: Macbook Pro
 - OS: macOS 10.13.6
 - Browser: Chrome
 - Version: 71.0.3578.98 (Official Build) (64-bit)
 - Angular 7.2

**Comment by jreeter** [comment] 2019-02-11 15:56
@CITguy any feedback on this?

**Comment by CITguy** [comment] 2019-02-11 16:45
We'll be working on a fix for this in our upcoming sprint.

**Comment by CITguy** [comment] 2019-02-13 16:58
JIRA: SURF-1569

**Comment by CITguy** [comment] 2019-04-25 17:23
FYI: A fix for this issue _may_ require breaking changes, in order to update the underlying behavior of tabsets.  If so, this will be _properly_ fixed for the `v0.17.0` release.  However, we'll look into getting a temporary patch or workaround in place for a `v0.16.x` release.

**Comment by CITguy** [comment] 2019-05-04 00:04
I cannot reproduce the error with `helix-ui v0.16.0`. I think it got fixed with updates in #484 (shipped with `v0.16.0` proper).

@jreeter, can you confirm this has been fixed?

**Comment by CITguy** [comment] 2019-05-08 18:08
Closing. Corrected in `v0.16.1` release.

**Closed by CITguy** 2019-05-08 18:08 UTC
Labels: BUG, JavaScript
