### ISSUE TITLE
Helix Search Input Firefox Issue

### ISSUE THREAD

**Issue by ssalinas24** [rackerlabs/helix-ui#212] opened 2018-04-27 20:06 UTC
Upon testing QE discovered bug with Recipients Search box in Firefox. However, it seems like the same issue would apply for all Search Boxes. The placeholder text shifts up vertically and is not vertically centered.

We have a defects on our Board that can be referenced.
https://jira.rax.io/browse/SDP-1039
https://jira.rax.io/browse/SDP-1094

**Comment by CITguy** [comment] 2018-05-14 17:07
I'm unable to reproduce at https://rackerlabs.github.io/helix-ui/components/search/ on Firefox 60. Can you check if a CSS selector in your application is being too greedy and applying a bottom margin to `input` elements?

**Comment by ssalinas24** [comment] 2018-06-22 21:14
@CITguy I created a story and already updated our CSS.
https://jira.rax.io/browse/SDP-1477

It was coming from here: https://github.rackspace.com/SDP/ConsolidatedTicketingUI/blob/master/src/styles.css#L120

Since hx-search produces a label and input, it was also receiving the bottom margin. Wish I could have seen this earlier, but we were moving super fast at the time. I should have looked into it my self prior. Thank you for taking the time to look into this.

**Comment by CITguy** [comment] 2018-07-16 18:12
Closing. Nothing to do.

**Closed by CITguy** 2018-07-16 18:12 UTC
