### ISSUE TITLE
Hx-File-Tile does not expand to meet its containers size

### ISSUE THREAD

**Issue by jonkruse00** [rackerlabs/helix-ui#323] opened 2018-08-27 15:21 UTC
## Describe the Bug
It would be nice if the `hx-file-tile` would expand to the containers width.

## Steps to Reproduce
Our implementation: 
```
  <div className="hxRow"> 
    <div className="hxCol hxSpan-12-xs hxSpan-6-sm hxSpan-4-lg">
      <HxFileTile
        data-tooltip={uuid}
        href={url}
        icon={icon}
        name={filename}
      />
      <hx-tooltip id={uuid} position="top" aria-hidden="true">
        {filename}
      </hx-tooltip>
    </div>
  </div>
```
![screen shot 2018-08-27 at 10 13 07 am](https://user-images.githubusercontent.com/5339195/44667965-d6b93d80-a9e1-11e8-813d-4b36c2caa424.png)

I found that if I attach an inline class I can get: 
```
  const hxFileTileStyle = {
    width: '100%',
    margin: '1%',
  };
  return (
  <div className={hxRow}>
    <div className={"hxCol hxSpan-12-xs hxSpan-6-sm hxSpan-4-lg"}>
      <HxFileTile
        data-tooltip={id}
        details={fileSize || undefined}
        href={url}
        icon={icon}
        name={filename}
        onDelete={() => removeAttachment(attachment)}

        progress={progress}
        style={hxFileTileStyle}
        {...getInvalidState(isValid, complete)}
      />
      {showErrorMessage && (
        <AttachmentErrorMessage errors={attachment.errors} />
      )}
      <hx-tooltip id={id} position="top" aria-hidden="true">
        {filename}
      </hx-tooltip>
    </div >
  </div>
```
![screen shot 2018-08-27 at 10 01 07 am](https://user-images.githubusercontent.com/5339195/44668053-17b15200-a9e2-11e8-8e08-7b23725e77f7.png)

But now the tile shows the ending of the file title. 

[HxFileTile](https://github.rackspace.com/SDP/ConsolidatedTicketingUI/blob/master/src/components/shared/HxFileTile.tsx) is a basic wrapper for `hx-file-tile`

## Expected behavior
The file tile expands width wise in the parent container. 

## Environment
Please complete the following information:

 - Device: Desktop
 - OS: iOS
 - Browser: chrome
 - Version: 48
 - Helix: 0.12.1

**Comment by CITguy** [comment] 2018-08-27 16:02
File tile width is fixed by design. This is to ensure consistent tiling when multiple files are present (similar to bottom screenshot of the prototype below)

<img width="853" alt="screen shot 2018-08-27 at 11 01 17 am" src="https://user-images.githubusercontent.com/545605/44670562-a45f0e80-a9e8-11e8-8756-8f43b67d6e74.png">


<img width="849" alt="screen shot 2018-08-27 at 11 01 05 am" src="https://user-images.githubusercontent.com/545605/44670563-a45f0e80-a9e8-11e8-80be-24322a1897d6.png">

**Comment by CITguy** [comment] 2018-12-11 16:16
Closing due to inactivity. Will reopen if still needed, later.

**Closed by CITguy** 2018-12-11 16:16 UTC
