### ISSUE TITLE
hx-Span6 fails to make columns 

### ISSUE THREAD

**Issue by jonkruse00** [rackerlabs/helix-ui#445] opened 2019-02-05 22:45 UTC
## Describe the Bug
Two `hx-span6`s do not make equal columns. Seems that the css rule `.hxRow > .hxCol {` applies padding which stops the columns from working properly

## Expected behavior
Make equal columns

## Screenshots
```html
<hx-tabpanel>
  <div className="hxRow">
    <div className="hxCol hxSpan-6">
      <span>left</span>
    </div>
    <div className="hxCol hxSpan-6">
      <span>right</span>
    </div>
  </div>
</hx-tabpanel>
```

## Environment
Please complete the following information:

 - Device: Desktop
 - OS: Ios
 - Browser: chrome
 - Version: 69

**Comment by jonkruse00** [comment] 2019-02-11 16:24
@CITguy
Here is my codepen version
https://codepen.io/anon/pen/OdZWoK?editors=1010#0

**Comment by CITguy** [comment] 2019-02-11 18:48
@jonkruse00: I'm seeing invalid markup in your codepen (invalid element nesting, `className` instead of `class`). Please correct and verify if you're still having an issue.

**Comment by TheNando** [comment] 2019-04-24 19:04
This seems to be working in the codepen example using the correct attribute. We still are having an issue on our side, but it is probably isolated to our implementation. We can close this issue and will open another if we end up verifying the cause being outside our control.

**Closed by TheNando** 2019-04-24 19:04 UTC
Labels: BUG, on hold
